### ISSUE TITLE
Configure CI

### ISSUE THREAD

**Issue by julianolf** [squad-4/loan-management-system#2]
- [x] Enable [Travis CI](https://docs.travis-ci.com/user/languages/python/) integration.
- [x] Add **initial*** `.travis.yml` configuration file. It should look like this:
```yaml
dist: xenial
language: python
cache: pip
python:
    - "3.7.3"
install:
    - pip install pipenv --upgrade
    - pipenv install --dev
script:
    - black --check
```

\* So far we don't have any test to run neither source code to check.
