### ISSUE TITLE
Configure pyup

### ISSUE THREAD

**Issue by julianolf** [squad-4/loan-management-system#3]
- [x] Enable [pyup](https://pyup.io) integration.
- [x] Add `.pyup.yml` configuration file as follow.
```yaml
schedule: "every week"
requirements:
  - Pipfile
  - Pipfile.lock
```
