### ISSUE TITLE
Add pre-commit rule (Black)

### ISSUE THREAD

**Issue by julianolf** [squad-4/loan-management-system#6]
Add a new rule for [pre-commit](https://pre-commit.com) in order to ensure that [Black](https://black.readthedocs.io) will enforce code style.

- [x] Create `.pre-commit-config.yaml` configuration file if it does not exists.
- [x] Add the following configuration:
```yaml
repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
```
